name: Python application

on:
  push:
    branches: [ "app" ]
  pull_request:
    branches: [ "app" ]

permissions:
  contents: read

jobs:

  build:

    # first operating system 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        make install 
    - name: Start FastAPI service
      run: |
        make serve &
        sleep 5  # Give the server some time to start
    - name: Wait for FastAPI service to start
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:8000/; then
            echo "Service is up!"
            break
          fi
          echo "Waiting for service to start..."
          sleep 5
        done
    - name: Test with pytest
      run: |
        make test 

    # second build command 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5 
        with: 
          python-version: "3.9"
      - name: Install Dependencies 
        run: make install 
      - name: Start Fastapi Service 
        run: |
          make serve && sleep 5 
      - name: Test with pytest 
        run: |
          make test 

